// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace StatSys
{
    internal sealed partial class Vsix
    {
        public const string Id = "StatSys.c2e267c0-e256-4af1-99bd-bd0e635c2176";
        public const string Name = "Stat Sys";
        public const string Description = @"Keeps track of your coding activity, the languages and projects you use and generates custom stat cards!";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "aisyshk";
        public const string Tags = "";
    }
}
